name = "gluegun_example_basic_request"
version = "0.1.0"
description = "Buildable basic request example for Gluegun"
licences = ["MIT"]
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.48.0 and < 2.0.0"
gluegun = { path = "../.." }
